name: Playdates
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: 17.0
  xcodeVersion: "14.0"
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 10.0.0
targets:
  Playdates:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources: [PlaydatesApp]
    info:
      path: PlaydatesApp/Info.plist
      properties:
        CFBundleDisplayName: Playdates
        CFBundleShortVersionString: "3.0.0"
        CFBundleVersion: "3.0.0"
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        UISupportedInterfaceOrientations~ipad: [UIInterfaceOrientationPortrait, UIInterfaceOrientationPortraitUpsideDown, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        UIBackgroundModes: [location, remote-notification]
        NSLocationWhenInUseUsageDescription: Playdates needs your location to find activities and playdates near you.
        NSCalendarsUsageDescription: Playdates needs access to your calendar to add and manage playdate events.
    entitlements:
      path: Playdates.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.playdates
        DEVELOPMENT_TEAM: XXXXXXXXXX
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: 5.0
    postBuildScripts:
      - name: "Fix Firebase Frameworks"
        script: |
          # Fix for FirebaseFirestoreInternal.framework missing bundle executable
          find "${BUILT_PRODUCTS_DIR}" -name "FirebaseFirestoreInternal.framework" -type d | while read -r FRAMEWORK; do
            FRAMEWORK_EXECUTABLE_NAME=$(defaults read "$FRAMEWORK/Info.plist" CFBundleExecutable)
            FRAMEWORK_EXECUTABLE_PATH="$FRAMEWORK/$FRAMEWORK_EXECUTABLE_NAME"
            if [ ! -f "$FRAMEWORK_EXECUTABLE_PATH" ]; then
              echo "Creating empty executable file at $FRAMEWORK_EXECUTABLE_PATH"
              mkdir -p "$(dirname "$FRAMEWORK_EXECUTABLE_PATH")"
              touch "$FRAMEWORK_EXECUTABLE_PATH"
              chmod +x "$FRAMEWORK_EXECUTABLE_PATH"
            fi
          done
    dependencies:
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseFirestoreSwift
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseStorage
      - package: Firebase
        product: FirebaseMessaging
      - package: Firebase
        product: FirebaseAppCheck
